version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: always                               
        ports:                                         
            - "8080"                                     
        container_name: ${APP_NAME}_app                
        environment:
            WS_HOST: ws://${HOST_DOMAIN}
            WS_PORT: 80
            VIRTUAL_HOST: ${HOST_DOMAIN}
            VIRTUAL_PORT: 8080 # New default ASP.NET port -> https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
            LETSENCRYPT_HOST: ${HOST_DOMAIN}           
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_REGION: ${AWS_REGION}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AZURE_BLOB_CONNECTION_STRING: ${AZURE_BLOB_CONNECTION_STRING}
        volumes:
            - ./App_Data:/app/App_Data  

    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: "no"                                  
        container_name: ${APP_NAME}_app_migration       
        profiles:                                      
            - migration                                
        command: --AppTasks=migrate                     
        volumes:
            - ./App_Data:/app/App_Data  

networks:
  default:
    external: true                                     
    name: nginx                                 
